spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: password

spring:
  h2:
    console:
      enabled: "true"

server:
  port: 8080
  servlet:
    context-path: /api/camunda-engine/